channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pyqt=5.12
  - pip
  - pillow
  - scipy
  - numba
  - pyqtgraph
  - vispy
  - pyopengl
  - pip:
    - inputs
    - git+https://github.com/pyqtgraph/pyqtgraph
    - git+https://github.com/alleninstitute/neuroanalysis
